declare const styles: {
  readonly "blink": string;
  readonly "chat-clear-btn": string;
  readonly "chat-confirm-no": string;
  readonly "chat-confirm-yes": string;
  readonly "chat-confirmation": string;
  readonly "chat-confirmation-actions": string;
  readonly "chat-cursor": string;
  readonly "chat-empty": string;
  readonly "chat-header": string;
  readonly "chat-input": string;
  readonly "chat-input-bar": string;
  readonly "chat-loading": string;
  readonly "chat-message": string;
  readonly "chat-message-assistant": string;
  readonly "chat-message-content": string;
  readonly "chat-message-streaming": string;
  readonly "chat-message-tool": string;
  readonly "chat-message-user": string;
  readonly "chat-messages": string;
  readonly "chat-model-error": string;
  readonly "chat-model-select": string;
  readonly "chat-send-btn": string;
  readonly "chat-tool-label": string;
  readonly "chat-tool-result": string;
  readonly "chat-view": string;
  readonly "modal-body-live-preview": string;
};
export = styles;

