declare const styles: {
  readonly "autotagChipInput": string;
  readonly "autotagTagInputWrapper": string;
  readonly "backdrop": string;
  readonly "chip": string;
  readonly "clearBtn": string;
  readonly "closeBtn": string;
  readonly "error": string;
  readonly "header": string;
  readonly "hint": string;
  readonly "keyActions": string;
  readonly "keyInput": string;
  readonly "keyRow": string;
  readonly "label": string;
  readonly "modal": string;
  readonly "ruleActions": string;
  readonly "ruleList": string;
  readonly "ruleMain": string;
  readonly "ruleRow": string;
  readonly "ruleTags": string;
  readonly "saveBtn": string;
  readonly "section": string;
  readonly "status": string;
  readonly "statusNone": string;
  readonly "statusOk": string;
  readonly "tab": string;
  readonly "tabActive": string;
  readonly "tabs": string;
  readonly "tagSuggestion": string;
  readonly "tagSuggestions": string;
  readonly "toggleRow": string;
};
export = styles;

